name: Wasm

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare cargo tests
      run: |
        rustup target add wasm32-unknown-emscripten --toolchain=nightly
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

    - name: Build for wasm
      run: cargo +nightly build --target=wasm32-unknown-emscripten -Zbuild-std=panic_abort,std

